### ISSUE TITLE
Website creation

### ISSUE THREAD

**Issue by tokorv** [BasedSoup/basedsoup.github.io#1]
Heads up, using basedsoup.github.io means your account will be limited to one website.
If you want to host multiple site for different projects you can just create a repository and the website's address will auto to basedsoup.github.io/repo_name.

I found this way better so I can split my github pages into multiple sites :)

**Comment by BasedSoup** [comment]
> Heads up, using basedsoup.github.io means your account will be limited to one website.
> If you want to host multiple site for different projects you can just create a repository and the website's address will auto to basedsoup.github.io/repo_name.
> 
> I found this way better so I can split my github pages into multiple sites :)

Oh epic, might look into that, for now I'm probably gonna try setting it up like a generic website cause then I can do a home page and stuff, but that's a good idea actually

**Comment by tokorv** [comment]
Edwin and I are making a forum over the half term. It's mainly just to put on our CVs and to get better at web stuff. You can join us if you like 😄

**Comment by BasedSoup** [comment]
> Edwin and I are making a forum over the half term. It's mainly just to put on our CVs and to get better at web stuff. You can join us if you like 😄

Yeah that sounds interesting, love me a good forum

**Comment by RemySzpuuk** [comment]
Yup good old forum website. Going to make it in html, css, javascript with a php backend. You want in? :P
